### ISSUE TITLE
Research Accelerometer and create test circuit

### ISSUE THREAD

**Issue by davidsw34** [cornellhyperloop/electrical#219]

**Comment by davidsw34** [comment]
Create a google doc with research, build the circuit, and write Arduino code to read live data
[Amazon Listing](https://www.amazon.com/HiLetgo-MPU-6050-Accelerometer-Gyroscope-Converter/dp/B01DK83ZYQ?th=1) (using this to keep track of the model number)

**Comment by ridhitbhura** [comment]
[Documentation](https://docs.google.com/document/d/1k-gkXAcEwGCUJEAu2SvlABhHxbCRAUctLqZNgm2l4I8/edit)
