### ISSUE TITLE
BMS assembly

### ISSUE THREAD

**Issue by robertchohfleming** [cornellhyperloop/electrical#296]
- Work with business to get necessary parts ordered 
- Come up with an assembly plan so we know what we need to do once parts arrive (look at what current parts we have and manual for help on this)
- Start work on the overall electrical power supply schematic (would do this in LT spice or even just google drawing)

**Comment by berkgokmen14** [comment]
https://docs.google.com/document/d/1TZFZp3ECOG4SBGkHl2tI3QZQT00YAYqdac4RjuP1KeA/edit

**Comment by mtrager22** [comment]
By end of sprint we: 
- Constructed schematic of BMS in google drawing
- Added items to budget, still need to figure out fuse situation
- Gained more info around wiring the BMS, still more to learn

This carries over into the next sprint
