### ISSUE TITLE
Laser Triangulation Sensors Research

### ISSUE THREAD

**Issue by ridhitbhura** [cornellhyperloop/electrical#297]
Laser Triangulation Sensors
https://www.althensensors.com/sensors/laser-position-sensors/single-point-triangulation-sensors/5114/fdrf603-series-laser-triangulation-sensor/

**Comment by zkarim28** [comment]
Laser Triangulation Sensor research: 
https://docs.google.com/document/d/1dx8bXwL7QHROUWMH30japPLyGn3c5dZmp4iuzIxzHMo/edit?usp=sharing 
https://docs.google.com/document/d/1dx8bXwL7QHROUWMH30japPLyGn3c5dZmp4iuzIxzHMo/edit?usp=sharing](url)
