### ISSUE TITLE
LIDAR Distance Sensor Research

### ISSUE THREAD

**Issue by ridhitbhura** [cornellhyperloop/electrical#298]
https://www.seeedstudio.com/Seeedstudio-Grove-TF-Mini-LiDAR.html?utm_source=blog&utm_medium=blog

**Comment by Levi2441** [comment]
https://docs.google.com/document/d/1-Klyp4prtbZXLmkJ2T8BrtdKtRoYgN2jj6rhKsInQII/edit?usp=sharing

**Comment by ridhitbhura** [comment]
Best out of the 3
