### ISSUE TITLE
Time of Flight Distance Sensor Research

### ISSUE THREAD

**Issue by ridhitbhura** [cornellhyperloop/electrical#299]
https://www.seeedstudio.com/Grove-Time-of-Flight-Distance-Sensor-VL53L0X.html?utm_source=blog&utm_medium=blog

**Comment by agh93** [comment]
[https://docs.google.com/document/d/1McZnm6m8IkQMiL-QZAWAH5g308aQv-QuudxOUc5bK4Q/edit?usp=sharing]
