### ISSUE TITLE
Create FSM test plan - documentation and code

### ISSUE THREAD

**Issue by ridhitbhura** [cornellhyperloop/electrical#315]
https://github.com/cornellhyperloop/electrical/blob/master/State_Estimation/src/statemachine.cpp

https://drive.google.com/drive/u/0/folders/1Km5-EVelO-qi-dWL58uK6_jURQFDM--z

**Comment by ridhitbhura** [comment]
https://drive.google.com/drive/u/0/folders/1Km5-EVelO-qi-dWL58uK6_jURQFDM--z

**Comment by ridhitbhura** [comment]
Creat test tutorial on Confluence @davidsw34 @Aimobhani9

**Comment by agh93** [comment]
Planning
[https://confluence.cornell.edu/display/culoop/FSM+Test+Cases](url)

**Comment by agh93** [comment]
Setup Google Test:
https://confluence.cornell.edu/display/culoop/How+to+use+Google+Test

4b causing error. First errors:
C:/Users/aghec/Documents/Cornell/hyperloop/electrical/State_Estimation/src/statemachine.cpp:239:3: error: 'WriteData' was not declared in this scope
  239 |   WriteData((char *)"Open", 4);
      |   ^~~~~~~~~
C:/Users/aghec/Documents/Cornell/hyperloop/electrical/State_Estimation/src/statemachine.cpp: In function 'void closeBrakes()':
C:/Users/aghec/Documents/Cornell/hyperloop/electrical/State_Estimation/src/statemachine.cpp:258:3: error: 'WriteData' was not declared in this scope
  258 |   WriteData((char *)"Close", 5);
      |   ^~~~~~~~~
C:/Users/aghec/Documents/Cornell/hyperloop/electrical/State_Estimation/src/statemachine.cpp:260:3: error: 'ReadData' was not declared in this scope; did you mean 'readData'?
  260 |   ReadData();
      |   ^~~~~~~~
      |   readData
C:/Users/aghec/Documents/Cornell/hyperloop/electrical/State_Estimation/src/statemachine.cpp: In function 'states accelerate(double, double)':
C:/Users/aghec/Documents/Cornell/hyperloop/electrical/State_Estimation/src/statemachine.cpp:277:6: error: expected '(' before 'checkDistance'
  277 |   if checkDistance (traveledDist, totalDist - decelRange)
      |      ^~~~~~~~~~~~~
      |      (
C:/Users/aghec/Documents/Cornell/hyperloop/electrical/State_Estimation/src/statemachine.cpp:281:3: error: 'else' without a previous 'if'
  281 |   else
      |   ^~~~
