### ISSUE TITLE
Braking Motor, Electromagnets, Solenoid Valve

### ISSUE THREAD

**Issue by berkgokmen14** [cornellhyperloop/electrical#357]
1) Contact people on mechanical to learn if they are planning to change their systems
2) If they are not planning to change, document the requirements for the braking motor, solenoid valve, and electromagnets

**Comment by stephenchien3** [comment]
As per Nikita:
LIM will be 150V 30A (will be varied at constant power) 3 phase, so about 10 hp
Electromagnets are not confirmed yet
Braking should not take too much power, as it is just (4?) stepper motors
