### ISSUE TITLE
Research pressure sensor

### ISSUE THREAD

**Issue by ridhitbhura** [cornellhyperloop/electrical#383]

**Comment by ridhitbhura** [comment]
https://www.amazon.com/dp/B0CFJ7QNT4/ref=sspa_dk_detail_4?psc=1&pd_rd_i=B0CFJ7QNT4&pd_rd_w=P6GLm&content-id=amzn1.sym.eb7c1ac5-7c51-4df5-ba34-ca810f1f119a&pf_rd_p=eb7c1ac5-7c51-4df5-ba34-ca810f1f119a&pf_rd_r=M0WFDHC5TMW6A99P68GD&pd_rd_wg=2OIwU&pd_rd_r=d2c7edef-70e2-47e0-90f7-49226473d510&s=automotive&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWw

**Comment by Levi2441** [comment]
https://confluence.cornell.edu/display/culoop/150+Psi+Fuel+Oil+Pressure
