### ISSUE TITLE
Collect all the sensors

### ISSUE THREAD

**Issue by roninsharma25** [cornellhyperloop/electrical#59]
Inventory what sensors we have and determine which sensors we want to use on the pod

**Comment by davidsw34** [comment]
Will be using the following sensors for the semester:
- Inductive Proximity Sensor
- Thermistors
- Orientation Sensor
- TOF Range Finder
- Accelerometer

All of these semesters are in the box by the cage (where the Raspberry Pi is)

If time:
- Ultrasonic sensors
- IMU
